basePath: /
definitions:
  model.AuthResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  model.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.RefreshRequest:
    properties:
      refresh_token:
        type: string
    type: object
  model.RegisterResponse:
    properties:
      message:
        type: string
      user_id:
        type: integer
    type: object
  model.User:
    properties:
      id:
        type: integer
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  title: API сервиса авторизации
  version: "1.0"
paths:
  /login:
    post:
      description: Функция для авторизации пользователя
      parameters:
      - description: Данные для авторизации пользователя
        in: body
        name: login_request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      responses:
        "200":
          description: Ответ с токенами
          schema:
            $ref: '#/definitions/model.AuthResponse'
        "400":
          description: Неверный запрос
          schema:
            type: string
        "401":
          description: Неверный логин или пароль
          schema:
            type: string
      summary: Авторизация пользователя
  /refresh:
    post:
      description: Функция для обновления токенов пользователя
      parameters:
      - description: Данные для обновления токена
        in: body
        name: refresh_request
        required: true
        schema:
          $ref: '#/definitions/model.RefreshRequest'
      responses:
        "200":
          description: Ответ с новым токеном
          schema:
            $ref: '#/definitions/model.AuthResponse'
        "400":
          description: Неверный запрос
          schema:
            type: string
        "401":
          description: Неверный токен
          schema:
            type: string
      summary: Обновление токена авторизации
  /register:
    post:
      description: Функция для регистрации нового пользователя
      parameters:
      - description: Данные пользователя для регистрации
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "200":
          description: Ответ с информацией о регистрации
          schema:
            $ref: '#/definitions/model.RegisterResponse'
        "400":
          description: Неверный запрос
          schema:
            type: string
        "405":
          description: Метод не разрешён
          schema:
            type: string
      summary: Регистрация нового пользователя
schemes:
- http
swagger: "2.0"
